#!/usr/bin/env bash
# Tells a story for each user in /etc/passwd
# shellcheck shell=bash
while IFS=: read -r username _ uid _ _ home shell
do
    echo "The user $username has the ID $uid and uses the shell $shell. Their home directory is $home."
done < /etc/passwd
