#!/usr/bin/env bash
# Calculates the average of numbers from standard input
# shellcheck shell=bash
sum=0
count=0

while read -r number
do
    sum=$((sum + number))
    count=$((count + 1))
done

if [ "$count" -ne 0 ]
then
    echo $((sum / count))
fi
