#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes using while loops
# shellcheck shell=bash
hour=0
while [ "$hour" -le 11 ]
do
    minute=0
    while [ "$minute" -le 59 ]
    do
        echo "$hour:$minute"
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done
