#!/usr/bin/env bash
# Checks the type of a file
# shellcheck shell=bash
i="school"
if [ "$i" -e ]
then
    if [ "$i" -f  ]
    then
        echo "$i is a regular file"
    elif [ "$i" -d ]
    then
        echo "$i is a directory"
    else
        echo "$i is another type of file"
    fi
else
    echo "$i does not exist"
fi
