#!/usr/bin/env bash
# Checks the type of a file
# shellcheck shell=bash
if [ -e "$1" ]
then
    if [ -f "$1" ]
    then
        echo "$1 is a regular file"
    elif [ -d "$1" ]
    then
        echo "$1 is a directory"
    else
        echo "$1 is another type of file"
    fi
else
    echo "$1 does not exist"
fi
